name: OpenAPI to Postman Collection

on:
  push:
    branches:
      - main  # Set to your default branch
    paths:
      - 'path/to/openapi.yaml'  # Path to your OpenAPI file

jobs:
  convert-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Postman Converter
      run: npm install -g openapi-to-postmanv2

    - name: Convert OpenAPI Spec to Postman Collection
      run: |
        openapi2postmanv2 -s path/to/openapi.yaml -o postman_collection.json --pretty

    - name: Update Postman Collection
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: |
        curl --location --request PUT 'https://api.getpostman.com/collections/{{collection_uid}}' \
        --header 'X-Api-Key: $POSTMAN_API_KEY' \
        --header 'Content-Type: application/json' \
        --data-binary "@postman_collection.json"
